### ISSUE TITLE
addImage

### ISSUE THREAD

**Issue by UnknowG** [kyranet/canvasConstructor#353]
Invalid or unexpected token
(node:85276) UnhandledPromiseRejectionWarning: TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.
    at Function.resolveFile (/home/ubuntu/Rox/node_modules/discord.js/src/util/DataResolver.js:109:11)
    at Function.resolveFile (/home/ubuntu/Rox/node_modules/discord.js/src/structures/APIMessage.js:292:41)
    at /home/ubuntu/Rox/node_modules/discord.js/src/structures/APIMessage.js:224:72
    at Array.map (<anonymous>)
    at APIMessage.resolveFiles (/home/ubuntu/Rox/node_modules/discord.js/src/structures/APIMessage.js:224:46)
    at TextChannel.send (/home/ubuntu/Rox/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:46)
    at Object.module.exports.run (/home/ubuntu/Rox/commands/xp/Leaderboard.js:20:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:85276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:85276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

--------------
![image](https://user-images.githubusercontent.com/51505384/88492638-6b50bf80-cfac-11ea-85d4-a7cf4660bedc.png)

I've been trying to do this for two days. It's breaking my head. Please help me. help me. help me. help me.

**Comment by kyranet** [comment]
I do not have your entire code, but what is happening here is that your code has 2 return types: `Buffer` and `undefined`.

In case your `try` branch fails, the `catch` branch will be called, and since there is nothing returning in there, it will result on this error.

## So why does it never work?

By default, `require` supports only JavaScript (`.js`, `.cjs`, and `.mjs`), Wasm (`.wasm`) and native bindings (`.node`). You're using it to load a PNG file.

## How can I solve this issue?

You have two options:

1. Remove the try/catch, let the error bubble up, this will fix your issue completely.
1. Use [`fs.promises`](https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_fs_promises_api), specifically `readFile`, you may use [`path.join`](https://nodejs.org/dist/latest-v14.x/docs/api/path.html#path_path_join_paths) alongside [`__dirname`](https://nodejs.org/dist/latest-v14.x/docs/api/modules.html#modules_dirname) to get the directory your module is in.

**Comment by UnknowG** [comment]
i don't very understand
