### ISSUE TITLE
Can't add text.

### ISSUE THREAD

**Issue by Sythe2954** [kyranet/canvasConstructor#41]
```  .setShadowColor("rgba(22, 22, 22, 1)") // This is a nice colour for a shadow.
  .setShadowOffsetY(5) // Drop the shadow by 5 pixels.
  .setShadowBlur(10) // Blur the shadow by 10.
  .save() // We should save the instance again.
  // This circle is 2 pixels smaller in the radius to prevent a pixel border.
  .addCircle(84, 90, 62)
  .addRoundImage(avatar, 20, 26, 128, 128, 64)
  .restore()
  .createBeveledClip(20, 138, 128, 32, 5)
  .setColor("#23272A")
  .addRect(20, 138, 128, 32)
  .restore()
  .setTextAlign("center")
  // Set the colour to white, since we have a dark background for all the text boxes.
  .setColor("#FFFFFF")
 
  .addText(name, 285, 54) // This doesn't appear.
  .addText(`Level: 0`, 84, 159) //This appears.
  .setTextAlign("left")

  .addText(`XP: 1`, 241, 136)//This doesn't.
  .restore()
  .toBuffer();
```

![](https://cdn.discordapp.com/attachments/532861625334628358/533676475862351892/profile.jpg)

The text on the 1st and 3rd rectangle doesn't work.

**Comment by kyranet** [comment]
That's because `.createBeveledClip(20, 138, 128, 32, 5)` was not wrapped in a save/restore chain, so everything that's getting drawn afterwards will only be drawn if it's inside the beveled clip.

```javascript
  // ...
  .save()
  .createBeveledClip(20, 138, 128, 32, 5)
  .setColor("#23272A")
  .addRect(20, 138, 128, 32)
  .restore()
  // ...
```

The `save()` then multiple `restore()` does not work because of how CanvasRenderingContext2D.restore works (check [here](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/restore)):

*The `CanvasRenderingContext2D.restore()` method of the Canvas 2D API restores the most recently saved canvas state by popping the top entry in the drawing state stack. If there is no saved state, this method does nothing.*

Which suggests the existence of a stack in the canvas rendering context's state, and popping it would remove the last saved state while mutating itself to have the last values. As you did one save and three restores, the first one restored to the previous state, and the 2 following did.

**Comment by kyranet** [comment]
The state stack would work similarly to this (to describe how save and restore works):

State stack:
```javascript
+-----------+-------+
+-----------+-------+
```

$ `.setColor('red')`
$ `.save()`

State stack:
```javascript
+-----------+-------+
| fillStyle | 'red' |
+-----------+-------+
```

$ `.setColor('blue')`
$ `.save()`
$ `.setColor('green')`

State stack:
```javascript
+-----------+--------+
| fillStyle | 'blue' |
+-----------+--------+
| fillStyle | 'red'  |
+-----------+--------+
```

$ `.restore()`

> Pops the last entry from the state stack and applies to the canvas rendering, applying all state changes from the last element, in this demonstration, this will change fillStyle to `'blue'`.

State stack:
```javascript
+-----------+-------+
| fillStyle | 'red' |
+-----------+-------+
```

$ `.restore()`

> Pops the last entry from the state stack

State stack:
```javascript
+-----------+-------+
+-----------+-------+
```

$ `.restore()`

> Does nothing

State stack:
```javascript
+-----------+-------+
+-----------+-------+
```

---

This is what's happening in your code, you have one `.save()` with three `.restore()`, the first `.restore()` finds an element in the stack, but the other two do not, doing nothing.

**Comment by kyranet** [comment]
Closing issue due to the lack of a response, feel free to re-open if you still have issues 😃!
